[project]
name = "mcp-learn-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ravinderdhokwal", email = "ravindercodes@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
mcp-learn-server = "mcp_learn_server:main"

[build-system]
requires = ["uv_build>=0.10.11,<0.11.0"]
build-backend = "uv_build"
